/* Generated by scripts/build-exam-bank.js. Answer order is preserved. */
window.MEDRECALL_EXAM_BANK = {
  "questions": [
    {
      "id": "pastmock-prototype-q001",
      "topic": "past-mock-exams",
      "text": "Which disease is transmitted by arthropods?",
      "answers": [
        "Vagabond's disease",
        "Scabies",
        "Plica polonica",
        "Filariasis"
      ],
      "correct": 3,
      "explanation": "Blood-sucking arthropods transmit blood and tissue parasites such as filarial worms. The other listed conditions are produced directly by arthropods rather than transmitted by them."
    },
    {
      "id": "pastmock-prototype-q003",
      "topic": "past-mock-exams",
      "text": "Which of the following is the embryo of cestodes?",
      "answers": [
        "Miracidium",
        "Oncosphere",
        "Larva",
        "Cysticercoid"
      ],
      "correct": 1,
      "explanation": "The mature cestode egg contains a six-hooked hexacanth embryo called the oncosphere. Cysticercoid is a later cystic larval stage."
    },
    {
      "id": "pastmock-prototype-q004",
      "topic": "past-mock-exams",
      "text": "Which of the following stages is diagnostic in trematode infections?",
      "answers": [
        "Cercaria",
        "Amastigote",
        "Mature cyst",
        "Egg"
      ],
      "correct": 3,
      "explanation": "The diagnostic stage of trematodes is the egg, which may be immature or mature and contains a miracidium. Cercariae or encysted metacercariae are infective stages."
    },
    {
      "id": "pastmock-prototype-q005",
      "topic": "past-mock-exams",
      "text": "In which of the following parasites are mature cysts responsible for human infection?",
      "answers": [
        "Fasciola species",
        "Giardia lamblia",
        "Ascaris lumbricoides",
        "Toxoplasma gondii"
      ],
      "correct": 1,
      "explanation": "Intestinal flagellates such as Giardia lamblia infect humans through ingestion of cysts in contaminated food or drink."
    },
    {
      "id": "pastmock-prototype-q006",
      "topic": "past-mock-exams",
      "text": "Where are venom glands present in scorpions?",
      "answers": [
        "Mouth",
        "Legs",
        "Telson",
        "Stinger"
      ],
      "correct": 2,
      "explanation": "Scorpions sting with the telson and inject venom produced in specialized venom glands there."
    },
    {
      "id": "pastmock-prototype-q007",
      "topic": "past-mock-exams",
      "text": "What is the main underlying cause of pain in furuncular myiasis?",
      "answers": [
        "Penetration of the larva into intact skin",
        "Larval growth inside the lesion",
        "Waste products of the larva",
        "Bacterial sepsis"
      ],
      "correct": 1,
      "explanation": "In furuncular myiasis, initial itching subsides and is replaced by more severe pain as the larva grows and becomes active within the boil-like swelling."
    },
    {
      "id": "pastmock-prototype-q008",
      "topic": "past-mock-exams",
      "text": "Which of the following, when present in stool, makes it pale in colour?",
      "answers": [
        "Blood",
        "Mucus",
        "Fat",
        "Pus"
      ],
      "correct": 2,
      "explanation": "Pale stool is associated with steatorrhoea, reflecting excess fat, as may occur with Giardia-related malabsorption."
    },
    {
      "id": "pastmock-prototype-q009",
      "topic": "past-mock-exams",
      "text": "Under the light microscope, water samples collected from water reservoirs revealed what is shown in the attached figure. Where does this parasite excyst?",
      "answers": [
        "Cecum",
        "Ileum",
        "Biliary tract",
        "Stomach"
      ],
      "correct": 1,
      "explanation": "The mature intestinal amoebic cyst is ingested and excysts in the small intestine; among the options, the ileum is the correct site.",
      "image": {
        "src": "assets/past-mock-exams/prototype/q009.webp",
        "alt": "Light microscopy image supplied with the original exam question"
      }
    },
    {
      "id": "pastmock-prototype-q010",
      "topic": "past-mock-exams",
      "text": "Which of the following tests is used to visualize the associated parasite while using a dye?",
      "answers": [
        "Indirect fluorescent antibody test",
        "Quantitative buffy coat technique",
        "ELISA technique",
        "Knott's technique"
      ],
      "correct": 1,
      "explanation": "The quantitative buffy coat technique uses an acridine orange fluorescent dye; stained parasites are concentrated near the buffy coat and visualized by fluorescence microscopy.",
      "image": {
        "src": "assets/past-mock-exams/prototype/q010.webp",
        "alt": "Blood film image with an arrow marking an intraerythrocytic structure"
      }
    },
    {
      "id": "pastmock-prototype-q011",
      "topic": "past-mock-exams",
      "text": "Blood examination of a male patient revealed the presence of the parasitic stage shown in the associated figure. To which of the following categories does this parasite belong?",
      "answers": [
        "Flagellates",
        "Sarcodina",
        "Apicomplexa",
        "Nematodes"
      ],
      "correct": 3,
      "explanation": "The image shows a blood-borne larval worm consistent with a microfilaria. Filarial worms belong to the phylum Nematoda, and tissue nematode larvae may be detected in blood.",
      "image": {
        "src": "assets/past-mock-exams/prototype/q011.webp",
        "alt": "Blood microscopy image of the parasitic stage supplied with the original exam question"
      }
    },
    {
      "id": "pastmock-prototype-q012",
      "topic": "past-mock-exams",
      "text": "Which of the following parasitic stages could be the infective stage of trematodes?",
      "answers": [
        "A",
        "B",
        "C",
        "D"
      ],
      "correct": 1,
      "explanation": "Panel B shows a cercarial form. The current source identifies either the cercaria or the encysted metacercaria as the infective stage of trematodes.",
      "image": {
        "src": "assets/past-mock-exams/prototype/q012.webp",
        "alt": "Four-panel montage of parasitic stages labeled A through D"
      }
    },
    {
      "id": "pastmock-prototype-q013",
      "topic": "past-mock-exams",
      "text": "A patient is suspected to have fascioliasis and his physician recommended a stool examination. Which of the following could be used for the appropriate concentration technique?",
      "answers": [
        "Formalin",
        "Sodium chloride",
        "Sodium hydroxide",
        "Zinc sulfate"
      ],
      "correct": 0,
      "explanation": "Fasciola produces heavy operculated eggs, for which sedimentation is appropriate. The formol-ether sedimentation technique uses formalin to fix and preserve specimens; flotation is poor for heavy operculated eggs."
    },
    {
      "id": "pastmock-prototype-q014",
      "topic": "past-mock-exams",
      "text": "A food handler complains of abdominal discomfort along with some gastrointestinal tract symptoms. Stool examination revealed mononucleated organisms. To which of the following parasitic categories could the causative agent belong?",
      "answers": [
        "Sarcodina",
        "Mastigophora",
        "Coccidia",
        "Nematodes"
      ],
      "correct": 0,
      "explanation": "Entamoeba histolytica is classified under Sarcodina, and its trophozoite is shown with a single nucleus. This fits the mononucleated intestinal organism described."
    },
    {
      "id": "pastmock-prototype-q015",
      "topic": "past-mock-exams",
      "text": "A 40-year-old woman complains of epigastric pain and jaundice. Stool examination revealed numerous oval eggs, each with a lid on one side. Which parasite could the causative agent be?",
      "answers": [
        "Taenia species",
        "Fasciola species",
        "Schistosoma species",
        "Ascaris lumbricoides"
      ],
      "correct": 1,
      "explanation": "A lid indicates an operculum. Trematodes lay operculated eggs except Schistosoma, whose eggs are non-operculated and spined; Fasciola is therefore the best answer."
    },
    {
      "id": "pastmock-prototype-q016",
      "topic": "past-mock-exams",
      "text": "A farmer noticed long white cylindrical worms in his stool during defecation. What is the kind of transmission of this infection?",
      "answers": [
        "Food-borne",
        "Airborne",
        "Iatrogenic",
        "Nosocomial"
      ],
      "correct": 0,
      "explanation": "The description is consistent with an intestinal nematode such as Ascaris. Intestinal nematode infection can follow ingestion of mature eggs in contaminated food or water, making food-borne transmission the best option."
    },
    {
      "id": "pastmock-prototype-q017",
      "topic": "past-mock-exams",
      "text": "Which of the following is the intracellular parasite that multiplies sexually in a vertebrate host?",
      "answers": [
        "Fasciola species",
        "Toxoplasma gondii",
        "Plasmodium species",
        "Taenia species"
      ],
      "correct": 1,
      "explanation": "Apicomplexa are intracellular parasites. Sexual reproduction of Toxoplasma gondii occurs in cats, a vertebrate host, whereas sexual reproduction of Plasmodium occurs in the mosquito."
    },
    {
      "id": "pastmock-prototype-q018",
      "topic": "past-mock-exams",
      "text": "What could be the diagnosis of the cutaneous lesion shown in the attached figure?",
      "answers": [
        "Scabies",
        "Creeping myiasis",
        "Furuncular myiasis",
        "Flea dermatitis"
      ],
      "correct": 2,
      "explanation": "Furuncular myiasis produces a boil-like swelling after a larva invades a hair follicle of intact skin. Creeping myiasis instead produces a serpiginous track.",
      "image": {
        "src": "assets/past-mock-exams/prototype/q018.webp",
        "alt": "Clinical photograph of a localized cutaneous lesion"
      }
    },
    {
      "id": "pastmock-prototype-q019",
      "topic": "past-mock-exams",
      "text": "A stained stool smear from a diarrheic sample showed the associated parasitic stage. How does this organism get rid of its waste products?",
      "answers": [
        "Excretion through contractile vacuoles",
        "Deposition as pigment granules",
        "Diffusion through the cytoplasmic membrane",
        "Release from slit-like openings"
      ],
      "correct": 2,
      "explanation": "The image shows an intestinal flagellate. The current source states that flagellates eliminate metabolic waste by diffusion through the ectoplasm, corresponding to diffusion across the cell surface.",
      "image": {
        "src": "assets/past-mock-exams/prototype/q019.webp",
        "alt": "Stained stool-smear microscopy image supplied with the original exam question"
      }
    },
    {
      "id": "pastmock-prototype-q020",
      "topic": "past-mock-exams",
      "text": "What is the indicator of the success of the test shown in the associated picture?",
      "answers": [
        "Two hours' test duration",
        "Low pH at the thread end",
        "Bile-stained thread end",
        "Dissolved gelatin capsule"
      ],
      "correct": 2,
      "explanation": "The duodenal capsule test samples duodenal contents. Recovery of bile-stained mucus from the thread shows that the sampling end reached the duodenum.",
      "image": {
        "src": "assets/past-mock-exams/prototype/q020.webp",
        "alt": "Clinical photograph of the sampling test shown in the original exam"
      }
    },
    {
      "id": "pastmock-prototype-q021",
      "topic": "past-mock-exams",
      "text": "A patient presented to the outpatient clinic with what is shown in the associated figure. What is the first complaint from this patient?",
      "answers": [
        "Purulent discharge",
        "Pain in the eye",
        "Bloody discharge",
        "Blurring of vision"
      ],
      "correct": 1,
      "explanation": "The current source states that severe eye pain is the first complaint in ocular myiasis.",
      "image": {
        "src": "assets/past-mock-exams/prototype/q021.webp",
        "alt": "Clinical photograph of an eye with structures supplied in the original exam"
      }
    },
    {
      "id": "pastmock-prototype-q022",
      "topic": "past-mock-exams",
      "text": "In an orphanage, an eight-year-old boy was highly irritable, crying all night and unable to sleep. His health care provider noticed multiple polymorphic skin lesions. Which of the following could be the causative agent?",
      "answers": [
        "Ticks",
        "Dermatophagoides",
        "Sarcoptes scabiei",
        "Dermatobia hominis"
      ],
      "correct": 2,
      "explanation": "Sarcoptes scabiei causes scabies, which spreads readily in crowded institutional settings and causes nocturnal itching with polymorphic skin lesions."
    },
    {
      "id": "pastmock-batch001-q001",
      "topic": "past-mock-exams",
      "text": "A 26-year-old woman reports painful micturition and other symptoms of urinary tract infection. Urine culture was performed and revealed the growth of Gram-positive cocci that were catalase test positive and coagulase test negative. The novobiocin test result is presented in this figure. What is the most likely organism to cause this infection?",
      "answers": [
        "Streptococcus pyogenes",
        "Staphylococcus aureus",
        "Staphylococcus saprophyticus",
        "Staphylococcus epidermidis"
      ],
      "correct": 2,
      "explanation": "Staphylococcus saprophyticus is a common cause of cystitis in women. It is catalase positive, coagulase negative, and resistant to novobiocin.",
      "image": {
        "src": "assets/past-mock-exams/batch-001/q001.webp",
        "alt": "Novobiocin susceptibility-test image supplied with the original examination question"
      }
    },
    {
      "id": "pastmock-batch001-q002",
      "topic": "past-mock-exams",
      "text": "An old woman developed massive reddish oedema of her leg following a small scratch. It spread rapidly to involve a large area of the leg. The pathogen isolated from a specimen collected from the lesion was a Gram-positive bacterium. What is the possible pathogen associated with this condition?",
      "answers": [
        "Pseudomonas aeruginosa",
        "Staphylococcus aureus",
        "Streptococcus pyogenes",
        "Escherichia coli"
      ],
      "correct": 2,
      "explanation": "Streptococcus pyogenes can cause erysipelas after entry through a minor cut or scratch, producing massive oedema with a rapidly advancing margin."
    },
    {
      "id": "pastmock-batch001-q003",
      "topic": "past-mock-exams",
      "text": "Which of the following bacterial structures is considered antiphagocytic?",
      "answers": [
        "Lipopolysaccharide",
        "Cell wall",
        "Capsule",
        "Flagella"
      ],
      "correct": 2,
      "explanation": "Polysaccharide capsules impede phagocytosis and are therefore important antiphagocytic virulence factors."
    },
    {
      "id": "pastmock-batch001-q004",
      "topic": "past-mock-exams",
      "text": "Medical students conducting a study on viral infections in children noted that RNA viral infections present with more evident flu-like symptoms, such as fever, bone pain, and malaise, than DNA viral infections. What is the justification of this observation?",
      "answers": [
        "RNA viruses are more potent type I interferon producers than DNA viruses",
        "Interferon gamma production is more stimulated by RNA viruses",
        "DNA viral infection stimulates production of immunomodulatory interferons",
        "DNA viral infection fails to induce type II interferons"
      ],
      "correct": 0,
      "explanation": "Double-stranded RNA formed during viral replication induces type I interferons, making RNA viruses stronger interferon inducers than DNA viruses."
    },
    {
      "id": "pastmock-batch001-q005",
      "topic": "past-mock-exams",
      "text": "To which class does this fungal morphology belong?",
      "answers": [
        "Mold",
        "Yeast",
        "Dimorphic",
        "Yeast-like"
      ],
      "correct": 2,
      "explanation": "Dimorphic fungi grow in a filamentous form at room temperature or in the environment and in a yeast form in the body or at 37°C.",
      "image": {
        "src": "assets/past-mock-exams/batch-001/q005.webp",
        "alt": "Paired fungal-growth morphologies supplied with the original examination question"
      }
    },
    {
      "id": "pastmock-batch001-q006",
      "topic": "past-mock-exams",
      "text": "What is transferred from one organism to another in the process of genetic engineering?",
      "answers": [
        "Enzymes",
        "DNA",
        "Proteins",
        "Ribosomes"
      ],
      "correct": 1,
      "explanation": "Genetic engineering transfers a selected DNA sequence into another organism or expression system so that the encoded product can be produced."
    },
    {
      "id": "pastmock-batch001-q007",
      "topic": "past-mock-exams",
      "text": "What is the term given to the number of bacteria required to cause infection?",
      "answers": [
        "Infective dose",
        "Virulence factor",
        "Log phase",
        "Colonization"
      ],
      "correct": 0,
      "explanation": "The infective dose is the number of organisms required to initiate infection or disease."
    },
    {
      "id": "pastmock-batch001-q008",
      "topic": "past-mock-exams",
      "text": "What is the term given to viral genetic material that acts directly as mRNA inside cells?",
      "answers": [
        "dsDNA",
        "dsRNA",
        "Positive-sense RNA",
        "Negative-sense RNA"
      ],
      "correct": 2,
      "explanation": "Positive-sense RNA has the same sense as mRNA and can therefore function directly as mRNA in the infected cell."
    },
    {
      "id": "pastmock-batch001-q009",
      "topic": "past-mock-exams",
      "text": "During which phase of its replication does the bacteriophage release muramidase?",
      "answers": [
        "Adsorption",
        "Penetration",
        "Eclipse",
        "Maturation"
      ],
      "correct": 1,
      "explanation": "During penetration, phage muramidase on the base plate weakens the bacterial cell wall so that the phage nucleic acid can be injected."
    },
    {
      "id": "pastmock-batch001-q011",
      "topic": "past-mock-exams",
      "text": "Which of the following cells are mainly concerned with future exposures to the same antigen?",
      "answers": [
        "Dendritic cells",
        "Memory B and T cells",
        "Neutrophils",
        "T lymphocytes"
      ],
      "correct": 1,
      "explanation": "Memory B and T cells persist after the first response and respond more rapidly and efficiently on later exposure to the same antigen."
    },
    {
      "id": "pastmock-batch001-q012",
      "topic": "past-mock-exams",
      "text": "Which of the following is the primary site of action of streptogramin antibiotics?",
      "answers": [
        "The ribosomes",
        "The porin channels",
        "The peptidoglycan layer",
        "The cytoplasmic membrane"
      ],
      "correct": 0,
      "explanation": "Streptogramins inhibit bacterial protein synthesis by acting on the 50S ribosomal subunit."
    },
    {
      "id": "pastmock-batch001-q013",
      "topic": "past-mock-exams",
      "text": "How can microorganisms become resistant to sulphonamides?",
      "answers": [
        "Produce enzymes that destroy the active drug",
        "Develop an altered structural target for the drug",
        "Develop an altered metabolic pathway that bypasses the reaction inhibited by the drug",
        "Reduce their permeability to the drug"
      ],
      "correct": 2,
      "explanation": "Sulphonamide resistance can result from an altered metabolic pathway that bypasses the inhibited reaction, such as use of preformed folic acid instead of extracellular PABA."
    },
    {
      "id": "pastmock-batch001-q014",
      "topic": "past-mock-exams",
      "text": "How can the logarithmic phase of the bacterial growth curve be described?",
      "answers": [
        "The rate of growth diminishes until the number of cells remains constant",
        "The cell divides by binary fission regularly at a constant maximal rate",
        "The bacterial population declines due to accumulation of toxic products",
        "It represents the time taken for the cells to adapt themselves to the new environment"
      ],
      "correct": 1,
      "explanation": "In the logarithmic phase, cells divide by binary fission at a constant maximal rate and the population increases exponentially."
    },
    {
      "id": "pastmock-batch001-q015",
      "topic": "past-mock-exams",
      "text": "What is the most likely virus shown in the associated figure?",
      "answers": [
        "Herpes simplex virus 1",
        "Epstein-Barr virus",
        "Cytomegalovirus",
        "Varicella-zoster virus"
      ],
      "correct": 3,
      "explanation": "Varicella-zoster virus causes primary varicella, remains latent in sensory ganglia, and can reactivate to produce herpes zoster in a dermatomal distribution.",
      "image": {
        "src": "assets/past-mock-exams/batch-001/q015.webp",
        "alt": "Diagram of primary infection, latency, and reactivation supplied with the original examination question"
      }
    },
    {
      "id": "pastmock-batch001-q016",
      "topic": "past-mock-exams",
      "text": "A patient is reviewed by a neurologist because of stiffness in her back. She was sent to the immunology lab. Results revealed the presence of HLA-B27. What clinical condition is this result suggestive of?",
      "answers": [
        "Rheumatoid arthritis",
        "Myasthenia gravis",
        "Multiple sclerosis",
        "Ankylosing spondylitis"
      ],
      "correct": 3,
      "explanation": "HLA-B27 is associated with ankylosing spondylitis."
    },
    {
      "id": "pastmock-batch001-q017",
      "topic": "past-mock-exams",
      "text": "In which of the following parasites are larvae responsible for human infection?",
      "answers": [
        "Ancylostoma duodenale",
        "Fasciola species",
        "Ascaris lumbricoides",
        "Toxoplasma gondii"
      ],
      "correct": 0,
      "explanation": "Ancylostoma duodenale infective larvae actively penetrate human skin. Fasciola infects through metacercariae, Ascaris through eggs, and Toxoplasma through other stages."
    },
    {
      "id": "pastmock-batch001-q018",
      "topic": "past-mock-exams",
      "text": "A 72-year-old female was diagnosed as a case of pneumonia and an antibacterial was given. Two days later, she presented with fever, hypertension, tachycardia, tremor, and hyperreflexia. Which of the following could be the cause of this adverse drug reaction?",
      "answers": [
        "Linezolid",
        "Ceftaroline",
        "Vancomycin",
        "Tigecycline"
      ],
      "correct": 0,
      "explanation": "Linezolid can inhibit monoamine oxidase and cause serotonin syndrome, which can present with autonomic overactivity, tremor, and hyperreflexia."
    },
    {
      "id": "pastmock-batch001-q019",
      "topic": "past-mock-exams",
      "text": "What are the components of a segmented viral genome?",
      "answers": [
        "More than one segment of nucleic acid",
        "Double-stranded RNA",
        "Positive-sense RNA and negative-sense RNA molecules",
        "Both RNA and DNA strands"
      ],
      "correct": 0,
      "explanation": "A segmented viral genome consists of more than one separate nucleic-acid segment; segmentation does not require a particular RNA sense or both DNA and RNA."
    },
    {
      "id": "pastmock-batch001-q020",
      "topic": "past-mock-exams",
      "text": "A patient suffers from urinary tract infection, and E. coli was isolated from culture of his urine sample. What is the interpretation of this result, knowing that the organism is part of the gastrointestinal bacterial flora?",
      "answers": [
        "Resident normal flora",
        "Opportunistic pathogen",
        "Commensal organism",
        "True pathogen"
      ],
      "correct": 1,
      "explanation": "E. coli normally inhabits the large intestine but can cause urinary tract infection when it enters another body system, so it acts as an opportunistic pathogen in this setting."
    },
    {
      "id": "pastmock-batch001-q021",
      "topic": "past-mock-exams",
      "text": "Which of the following conditions is associated with HHV-6?",
      "answers": [
        "Infectious mononucleosis",
        "Roseola infantum",
        "Herpes labialis",
        "Kaposi's sarcoma"
      ],
      "correct": 1,
      "explanation": "Primary HHV-6 infection is associated with exanthem subitum, also called roseola infantum or sixth disease."
    },
    {
      "id": "pastmock-batch001-q022",
      "topic": "past-mock-exams",
      "text": "Which of the following is the prodrug of acyclovir?",
      "answers": [
        "Ganciclovir",
        "Sofosbuvir",
        "Valacyclovir",
        "Tenofovir"
      ],
      "correct": 2,
      "explanation": "The supplied historical answer identifies valacyclovir. The current course source lists valacyclovir among drugs effective against herpes simplex infection but does not state the prodrug relationship explicitly."
    },
    {
      "id": "pastmock-batch001-q023",
      "topic": "past-mock-exams",
      "text": "Which of the following is a character of a prokaryotic cell?",
      "answers": [
        "Presence of a nucleus",
        "Ribosome size is 80S",
        "Membrane-bound organelles",
        "Unicellular"
      ],
      "correct": 3,
      "explanation": "Prokaryotic bacteria are unicellular and lack a nucleus and membrane-bound organelles; their ribosomes are 70S rather than 80S."
    },
    {
      "id": "pastmock-batch001-q024",
      "topic": "past-mock-exams",
      "text": "A 40-year-old woman complains of epigastric pain and jaundice. Stool examination revealed numerous oval eggs, each with a lid on one side. Which of the following is specific for the causative agent?",
      "answers": [
        "Parthenogenetic",
        "Monogenetic",
        "Digenetic",
        "Viviparous"
      ],
      "correct": 2,
      "explanation": "The operculated eggs and biliary presentation indicate a trematode. Trematodes are digenetic, with sexual reproduction in a definitive host and asexual reproduction in an intermediate host."
    },
    {
      "id": "pastmock-batch001-q025",
      "topic": "past-mock-exams",
      "text": "A patient was admitted to hospital with a large burn injury. After two days he became feverish and the burn became infected. A sample from the wound was cultured and revealed growth of an organism with diffusible greenish pigments. Which is the likely causative organism?",
      "answers": [
        "Proteus",
        "Klebsiella",
        "Acinetobacter",
        "Pseudomonas"
      ],
      "correct": 3,
      "explanation": "Pseudomonas aeruginosa characteristically produces diffusible greenish pigments and is an important cause of burn-wound infection."
    },
    {
      "id": "pastmock-batch001-q026",
      "topic": "past-mock-exams",
      "text": "Which of the following is a major difference between a lysogenic and a lytic cycle in bacteriophages?",
      "answers": [
        "Viral DNA becomes a physical part of the bacterial chromosome only in a lysogenic cycle",
        "A lysogenic virus directs the production of new viruses right away",
        "Viral DNA is inserted into the bacterial cell only in a lytic cycle",
        "The bacteriophage attaches to bacterial surface receptor proteins only in a lysogenic cycle"
      ],
      "correct": 0,
      "explanation": "In lysogeny, the phage genome integrates into the bacterial chromosome as a prophage without immediately killing the host cell."
    },
    {
      "id": "pastmock-batch001-q027",
      "topic": "past-mock-exams",
      "text": "Which of the following describes dimorphism in Candida?",
      "answers": [
        "Ability to undergo mitosis as well as meiosis",
        "Ability to develop spherical and elongated forms of nuclei",
        "Capability to grow in two different forms",
        "Ability to produce two types of spores"
      ],
      "correct": 2,
      "explanation": "Candida can occur as budding yeast-like cells and as elongated pseudohyphal forms, corresponding to growth in two morphological forms."
    },
    {
      "id": "pastmock-batch001-q028",
      "topic": "past-mock-exams",
      "text": "What is the type of microbial sensor marked by the arrow in the given figure?",
      "answers": [
        "PAMPs",
        "CD28",
        "NOD-like receptors",
        "Toll-like receptors"
      ],
      "correct": 3,
      "explanation": "The figure shows a membrane pattern-recognition receptor activating NF-κB and inflammatory reactions. Cell-surface Toll-like receptors recognize extracellular microbial PAMPs and trigger this response.",
      "image": {
        "src": "assets/past-mock-exams/batch-001/q028.webp",
        "alt": "Innate-immune receptor signaling diagram supplied with the original examination question"
      }
    },
    {
      "id": "pastmock-batch001-q029",
      "topic": "past-mock-exams",
      "text": "A 30-year-old immunocompromised patient is scheduled for vaccination. What type of vaccine technology would you approve?",
      "answers": [
        "Avirulent vector vaccine",
        "Vaccine utilising less virulent mutants",
        "Vaccine that utilizes killed organisms",
        "Live vaccines attenuated by genetic engineering"
      ],
      "correct": 2,
      "explanation": "Inactivated vaccines contain killed organisms and can be given safely to immunocompromised patients, whereas live attenuated approaches are contraindicated."
    },
    {
      "id": "pastmock-batch001-q030",
      "topic": "past-mock-exams",
      "text": "A 10-week-old infant presents to hospital with fever and neck rigidity. Lumbar puncture reveals numerous neutrophils and Gram-positive bacteria. Upon admission, IV β-lactams were started. Which of the following targets would most likely play a role in the development of resistance to this antibiotic?",
      "answers": [
        "Penicillin-binding proteins",
        "50S ribosomal subunit",
        "DNA gyrase",
        "30S ribosomal subunits"
      ],
      "correct": 0,
      "explanation": "β-Lactams bind penicillin-binding proteins, and loss or alteration of these proteins can produce resistance."
    },
    {
      "id": "pastmock-batch001-q031",
      "topic": "past-mock-exams",
      "text": "Which of the following is used for treatment of intestinal cestode infection?",
      "answers": [
        "Metronidazole",
        "Ivermectin",
        "Praziquantel",
        "Albendazole"
      ],
      "correct": 2,
      "explanation": "The supplied historical answer identifies praziquantel. The current supplied course sources do not provide enough treatment detail to independently verify this item."
    },
    {
      "id": "pastmock-batch001-q032",
      "topic": "past-mock-exams",
      "text": "While a housewife was preparing beef meat, she observed what is shown in the attached figure. To which parasite category does this parasitic stage belong?",
      "answers": [
        "Sarcodina",
        "Cestodes",
        "Trematodes",
        "Nematodes"
      ],
      "correct": 1,
      "explanation": "The white cystic structures in beef represent a cystic larval stage of a tapeworm; tapeworms belong to the class Cestoidea.",
      "image": {
        "src": "assets/past-mock-exams/batch-001/q032.webp",
        "alt": "Photograph of beef tissue containing pale cystic structures supplied with the original examination question"
      }
    },
    {
      "id": "pastmock-batch001-q033",
      "topic": "past-mock-exams",
      "text": "Which organism respires in the presence of oxygen and ferments in its absence?",
      "answers": [
        "Obligate aerobe",
        "Obligate anaerobe",
        "Facultative aerobe",
        "Facultative anaerobe"
      ],
      "correct": 3,
      "explanation": "Facultative anaerobes grow with or without oxygen, using aerobic respiration when oxygen is present and anaerobic respiration or fermentation when it is absent."
    },
    {
      "id": "pastmock-batch001-q034",
      "topic": "past-mock-exams",
      "text": "A 24-year-old lady experienced a sudden onset of high fever, myalgia, vomiting, and diarrhea. Three days before, she underwent a surgical procedure and the surgical wound started to ooze pus the next day. Culture of pus from the infected wound revealed beta-haemolytic colonies on blood agar. Colonies were catalase positive and fermented mannitol. What is the most likely causative organism?",
      "answers": [
        "Staphylococcus epidermidis",
        "Staphylococcus saprophyticus",
        "Staphylococcus aureus",
        "Streptococcus pyogenes"
      ],
      "correct": 2,
      "explanation": "Staphylococcus aureus is catalase positive, commonly beta-haemolytic, and ferments mannitol; these findings distinguish it from the other listed organisms."
    },
    {
      "id": "pastmock-batch001-q035",
      "topic": "past-mock-exams",
      "text": "The Gram-stained film of a throat swab culture from a case of tonsillitis reveals Gram-positive cocci arranged as shown in the associated figure. Which of the following is a major character of these cocci?",
      "answers": [
        "Catalase enzyme is produced by all strains",
        "O antigen is the major surface antigen",
        "M protein is the virulence factor",
        "Porins are always present in the cell wall"
      ],
      "correct": 2,
      "explanation": "The cocci in chains are consistent with Streptococcus pyogenes. Its M protein is a major virulence factor that inhibits phagocytosis.",
      "image": {
        "src": "assets/past-mock-exams/batch-001/q035.webp",
        "alt": "Gram-stained microscopy image supplied with the original examination question"
      }
    },
    {
      "id": "pastmock-batch001-q036",
      "topic": "past-mock-exams",
      "text": "Which one of the following best describes the mode of action of cephalosporins?",
      "answers": [
        "Inhibits transcription of bacterial mRNA",
        "Inhibits folic acid synthesis",
        "Binds to the 30S ribosome and inhibits bacterial protein synthesis",
        "Inhibits peptidoglycan synthesis"
      ],
      "correct": 3,
      "explanation": "Cephalosporins are β-lactam drugs that inhibit bacterial cell-wall peptidoglycan synthesis in the same manner as penicillins."
    },
    {
      "id": "pastmock-batch001-q037",
      "topic": "past-mock-exams",
      "text": "What is the main structure in Gram-negative bacteria that discriminates them from Gram-positive ones?",
      "answers": [
        "Polysaccharides",
        "Cytoplasmic membrane",
        "Teichoic acids",
        "Outer membrane"
      ],
      "correct": 3,
      "explanation": "Gram-negative bacteria possess an outer membrane external to their thin peptidoglycan layer; Gram-positive bacteria lack this membrane."
    },
    {
      "id": "pastmock-batch001-q038",
      "topic": "past-mock-exams",
      "text": "Which of the following is given by the oral route to treat toenail dermatophyte infection?",
      "answers": [
        "Nystatin",
        "Ketoconazole",
        "Terbinafine",
        "Amphotericin B"
      ],
      "correct": 2,
      "explanation": "Terbinafine is an effective systemic treatment for dermatophyte infection, including infection of the nail."
    },
    {
      "id": "pastmock-batch001-q039",
      "topic": "past-mock-exams",
      "text": "A 22-year-old female presents with a 2-day history of dysuria with increased urinary frequency and urgency. A urine culture showed E. coli. Which one of the following would be a wrong antibacterial for this patient?",
      "answers": [
        "Levofloxacin",
        "Moxifloxacin",
        "Nitrofurantoin",
        "Cotrimoxazole"
      ],
      "correct": 1,
      "explanation": "Moxifloxacin is hepatically metabolized and is listed for respiratory and intra-abdominal infections rather than urinary tract infection, unlike the other options."
    },
    {
      "id": "pastmock-batch001-q040",
      "topic": "past-mock-exams",
      "text": "For whom of the following is teicoplanin preferred over vancomycin for treatment of MRSA infection?",
      "answers": [
        "Patients with chronic renal diseases",
        "Elderly patients",
        "Patients with lung infection",
        "Pregnant patients"
      ],
      "correct": 0,
      "explanation": "Teicoplanin is less nephrotoxic than vancomycin and is therefore preferred in patients at high risk of renal toxicity, such as those with chronic renal disease."
    },
    {
      "id": "pastmock-batch001-q041",
      "topic": "past-mock-exams",
      "text": "A young man developed the lesion shown in the opposite figure after being bitten by an arthropod. By which arthropod was this patient bitten?",
      "answers": [
        "Bed bug",
        "Sand fly",
        "Itch mite",
        "Mosquito"
      ],
      "correct": 1,
      "explanation": "The ulcerative lesion is consistent with cutaneous leishmaniasis, and Leishmania species are transmitted by sand flies.",
      "image": {
        "src": "assets/past-mock-exams/batch-001/q041.webp",
        "alt": "Clinical photograph of a cutaneous lesion supplied with the original examination question"
      }
    },
    {
      "id": "pastmock-batch001-q042",
      "topic": "past-mock-exams",
      "text": "What is the name of the process in which the bacteria make many copies of the recombinant plasmid, and the copied human gene is harvested from the cells?",
      "answers": [
        "Conjugation",
        "Transformation",
        "Gene cloning",
        "Recombination"
      ],
      "correct": 2,
      "explanation": "Gene cloning uses a recombinant plasmid in bacteria or yeast so that the inserted gene is copied and expressed for later recovery of its product."
    },
    {
      "id": "pastmock-batch001-q043",
      "topic": "past-mock-exams",
      "text": "A diabetic farmer has been hospitalized to adjust his uncontrolled blood sugar level. The attending nurse noticed the presence of a small wound in his left leg. Three days later, the patient suffered from severe pain in his wound and the nurse noticed small worm-like organisms in it. What could be the source of this infestation?",
      "answers": [
        "Contaminated food",
        "Soiled latrine",
        "Nosocomial",
        "Iatrogenic"
      ],
      "correct": 2,
      "explanation": "The infestation appeared during hospitalization and was not present at admission. This fits a nosocomial parasitic infection; myiasis is a listed example."
    },
    {
      "id": "pastmock-batch001-q044",
      "topic": "past-mock-exams",
      "text": "Which immunoglobulin is elevated in the serum of allergic individuals?",
      "answers": [
        "IgG",
        "IgA",
        "IgM",
        "IgE"
      ],
      "correct": 3,
      "explanation": "Serum IgE is elevated in allergic individuals and plays a central role in type I hypersensitivity."
    },
    {
      "id": "pastmock-batch001-q045",
      "topic": "past-mock-exams",
      "text": "Light microscopic examination of a soil sample revealed what is shown in the opposite figure. What is the route of transmission of this parasite stage?",
      "answers": [
        "Direct contact with infected person",
        "Skin penetration",
        "Food-borne",
        "Airborne"
      ],
      "correct": 2,
      "explanation": "The image shows an Ascaris egg. Human infection follows ingestion of infective eggs from contaminated food, water, fingers, or soil, so food-borne transmission is the best option.",
      "image": {
        "src": "assets/past-mock-exams/batch-001/q045.webp",
        "alt": "Light-microscopy image of a helminth egg supplied with the original examination question"
      }
    },
    {
      "id": "pastmock-batch001-q046",
      "topic": "past-mock-exams",
      "text": "Which of the following cytokines damp down the immune response?",
      "answers": [
        "Colony-stimulating factor",
        "Interferon gamma",
        "Tumor necrosis factor",
        "Transforming growth factor beta"
      ],
      "correct": 3,
      "explanation": "Transforming growth factor beta is an immunosuppressive, anti-inflammatory cytokine that downregulates immune responses."
    },
    {
      "id": "pastmock-batch001-q047",
      "topic": "past-mock-exams",
      "text": "Which of the marked bacterial structures is responsible for attachment of the bacteria to the host cell?",
      "answers": [
        "B",
        "D",
        "C",
        "A"
      ],
      "correct": 1,
      "explanation": "Label D marks the short common pili or fimbriae. These structures mediate bacterial adhesion to host cells.",
      "image": {
        "src": "assets/past-mock-exams/batch-001/q047.webp",
        "alt": "Labeled bacterial-cell diagram supplied with the original examination question"
      }
    },
    {
      "id": "pastmock-batch001-q048",
      "topic": "past-mock-exams",
      "text": "What is the specific feature of the developed larvae in complete metamorphosis?",
      "answers": [
        "Morphologically similar to the adults",
        "Transform into pupa",
        "Increase in size by successive molting",
        "Metabolically inactive"
      ],
      "correct": 1,
      "explanation": "In complete metamorphosis, larvae differ morphologically from adults and transform into an inactive pupal stage before becoming adults."
    },
    {
      "id": "pastmock-batch001-q049",
      "topic": "past-mock-exams",
      "text": "Which immunoglobulin is the most predominant in serum?",
      "answers": [
        "IgA",
        "IgE",
        "IgG",
        "IgM"
      ],
      "correct": 2,
      "explanation": "IgG forms about 75% of serum immunoglobulins and is therefore the predominant class in serum."
    },
    {
      "id": "pastmock-batch001-q050",
      "topic": "past-mock-exams",
      "text": "A young boy presented to the outpatient clinic with the complaint shown in the figure. A Gram-stained smear from the skin lesions showed frequent pus cells with Gram-positive cocci arranged in chains. What is the most likely causative agent?",
      "answers": [
        "Staphylococcus aureus",
        "Escherichia coli",
        "Staphylococcus epidermidis",
        "Streptococcus pyogenes"
      ],
      "correct": 3,
      "explanation": "Gram-positive cocci in chains indicate streptococci, and Streptococcus pyogenes causes streptococcal pyoderma or impetigo in children.",
      "image": {
        "src": "assets/past-mock-exams/batch-001/q050.webp",
        "alt": "Clinical photograph of a child's facial skin lesion supplied with the original examination question"
      }
    },
    {
      "id": "pastmock-batch001-q051",
      "topic": "past-mock-exams",
      "text": "Which of the following is the correct description of how to prepare an inactivated vaccine by recombinant technique?",
      "answers": [
        "Exposure of a wild-type virulent virus to a chemical agent to lose infectivity",
        "Insertion of DNA encoding the immunizing antigen in yeast cells expressing the antigen",
        "Wild-type virus attenuation by growth under non-physiological conditions",
        "Enhancing immunogenicity by linking it to a protein carrier"
      ],
      "correct": 1,
      "explanation": "Recombinant protein vaccines are produced by inserting DNA encoding the immunizing antigen into yeast cells, which express the antigen for purification and use as the vaccine component."
    },
    {
      "id": "pastmock-batch001-q052",
      "topic": "past-mock-exams",
      "text": "An indirect haemagglutination test was performed for a patient suspected to have Schistosoma haematobium infection and revealed the shown figure. How did the patient's urine sample look macroscopically?",
      "answers": [
        "Smoky",
        "Milky white",
        "Clear",
        "Turbid"
      ],
      "correct": 0,
      "explanation": "Schistosoma haematobium infection causes haematuria. Blood gives the urine a smoky appearance on macroscopic examination.",
      "image": {
        "src": "assets/past-mock-exams/batch-001/q052.webp",
        "alt": "Indirect haemagglutination test image supplied with the original examination question"
      }
    },
    {
      "id": "pastmock-batch002-q001",
      "topic": "past-mock-exams",
      "text": "What is the recommended duration of storage of the vaccine at the district level?",
      "answers": [
        "3 months",
        "2 months",
        "1 month",
        "6 months"
      ],
      "correct": 2,
      "explanation": "The marked district-level storage interval in the source question is 1 month."
    },
    {
      "id": "pastmock-batch002-q002",
      "topic": "past-mock-exams",
      "text": "Which antibacterial could predispose to cardiac arrhythmia?",
      "answers": [
        "Doxycycline",
        "Piperacillin",
        "Gentamicin",
        "Clarithromycin"
      ],
      "correct": 3,
      "explanation": "Clarithromycin is a macrolide; the course source lists QT prolongation and torsades de pointes as macrolide-related cardiac risks."
    },
    {
      "id": "pastmock-batch002-q003",
      "topic": "past-mock-exams",
      "text": "What characterizes a disease caused by a microorganism with “high pathogenicity”?",
      "answers": [
        "Spread rapidly among the population from person to person",
        "Manifest clinically among large proportion of infected persons",
        "Result in a lifelong immunity following a single episode of illness",
        "Causes severe illness associated with high rates of mortality"
      ],
      "correct": 1,
      "explanation": "The key distinction in the supplied answer is that a large proportion of infected people develop clinical illness, rather than merely having rapid spread or high mortality."
    },
    {
      "id": "pastmock-batch002-q004",
      "topic": "past-mock-exams",
      "text": "A 23-years old patient was presented to clinic with severe diarrhea and bloody stool. He gave history of use of oral broad spectrum antibacterial. Which antibacterial would be used to treat this patient?",
      "answers": [
        "Azithromycin",
        "Ampicillin",
        "Vancomycin",
        "Ciprofloxacin"
      ],
      "correct": 2,
      "explanation": "Broad-spectrum antibiotic exposure can precede C. difficile colitis; the course source lists oral vancomycin for its treatment."
    },
    {
      "id": "pastmock-batch002-q005",
      "topic": "past-mock-exams",
      "text": "Which pattern of disease occurrence is classified as “sporadic”?",
      "answers": [
        "Sudden increase in the number of cases of typhoid fever over 2-week period",
        "Several cases of chickenpox among preschool children scattered over a year",
        "Increase in the number of cases of influenza among elderly in winter season",
        "Excess cases of diarrhea among children attending schools in only one district"
      ],
      "correct": 1,
      "explanation": "The marked example consists of cases scattered over time, rather than a sudden increase or seasonal concentration."
    },
    {
      "id": "pastmock-batch002-q006",
      "topic": "past-mock-exams",
      "text": "For whom the empiric use of a combination of antimicrobials is indicated?",
      "answers": [
        "Critically ill patient with severe infection",
        "Elderly with prostatitis",
        "Adult with Syphilis",
        "Child with pharyngitis"
      ],
      "correct": 0,
      "explanation": "The course source supports broader initial combination coverage in life-threatening infection while culture results are pending."
    },
    {
      "id": "pastmock-batch002-q007",
      "topic": "past-mock-exams",
      "text": "Which antibacterial is used for treatment of syphilis?",
      "answers": [
        "Erythromycin",
        "Gentamicin",
        "Doxycycline",
        "Cotrimoxazole"
      ],
      "correct": 2,
      "explanation": "The course source lists doxycycline as an alternative for syphilis in patients allergic to penicillin."
    },
    {
      "id": "pastmock-batch002-q008",
      "topic": "past-mock-exams",
      "text": "Which antibacterial is a beta lactamase-resistant penicillin?",
      "answers": [
        "Ampicillin",
        "Penicillin G",
        "Cloxacillin",
        "Penicillin V"
      ],
      "correct": 2,
      "explanation": "Cloxacillin belongs to the beta-lactamase-resistant antistaphylococcal penicillins described in the course source."
    },
    {
      "id": "pastmock-batch002-q009",
      "topic": "past-mock-exams",
      "text": "A 65-year-old patient was hospitalized for urinary retention. Urinary catheter was inserted to relieve the obstruction. Two days after hospitalization, the urine turned turbid. Urine examination showed many pus cells and gram-negative bacilli. Which antibacterial should be used in treatment of this case?",
      "answers": [
        "Doxycycline",
        "Azithromycin",
        "Ceftazidime",
        "Penicillin G"
      ],
      "correct": 2,
      "explanation": "Ceftazidime has broad Gram-negative activity, including Pseudomonas, and third-generation cephalosporins are listed for complicated urinary tract infection."
    },
    {
      "id": "pastmock-batch002-q010",
      "topic": "past-mock-exams",
      "text": "A patient presents to the clinic with low grade fever due to lower respiratory tract infection. How could isolation of staphylococcus species, from his nose be interpreted?",
      "answers": [
        "True pathogen",
        "Opportunistic agent",
        "Normal flora",
        "A cause of infection"
      ],
      "correct": 2,
      "explanation": "Staphylococci can normally colonize the respiratory tract, and nasal carriage of S. aureus is common. A nasal isolate alone does not establish the cause of a lower respiratory infection."
    },
    {
      "id": "pastmock-batch002-q011",
      "topic": "past-mock-exams",
      "text": "Which of the following does show morphological changes without increase in burden in its vector?",
      "answers": [
        "Yersinia pestis",
        "Filarial worms",
        "Plasmodium species",
        "Leishmania species"
      ],
      "correct": 1,
      "explanation": "Filarial microfilariae develop in mosquitoes without multiplying. The course source calls this cyclodevelopmental transmission."
    }
  ],
  "cases": {}
};
